spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resources/**
        - id: songs-service
          uri: lb://songs-service
          predicates:
            - Path=/songs/**
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/storages/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 8080
