server:
  port: 0      # Dynamic port assignment (to avoid conflicts)

spring:
  application:
    name: default-application

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
