spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  server:
    use-read-only-response-cache: false
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
