spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  server:
    use-read-only-response-cache: false
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
logstash:
  host: logstash
  port: 5044
