spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: defaultUser
    password: defaultPassword
  application:
    name: resource-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://resource-db:5432/resource-db
    username: postgres
    password: postgres
server:
  port: 8084
songs:
  service:
    eureka:
      id: songs-service
eureka:
  client:
    registry-fetch-interval-seconds: 1
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
cloud:
  storage:
    s3:
      uri: http://localstack:4566
      key: test
      secret: test
      region: eu-west-3
      resources:
        bucket: resources
rabbit:
  mq:
    resources:
      queue:
        name: resources
      routingKey: '#.resources'
      topic: resources_exchange
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
