spring:
  application:
    name: resource-processor
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: defaultUser
    password: defaultPassword
server:
  port: 8083
rabbit:
  mq:
    topic: resources_exchange
    resources_upload:
      queue:
        name: resource_upload
    resources_processed:
      routingKey: '#.resources_processed'
songs:
  service:
    eureka:
      id: songs-service
resource:
  service:
    eureka:
      id: resource-service
eureka:
  client:
    registry-fetch-interval-seconds: 1
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
retry:
  max:
    attempts: 6
  backoff:
    delay: 2000
    multiplier: 1.5
logstash:
  host: logstash
  port: 5044
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
