spring:
  application:
    name: storage-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://storage-db:5432/storage-db
    username: postgres
    password: postgres
server:
  port: 8089
eureka:
  client:
    registry-fetch-interval-seconds: 1
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
logstash:
  host: logstash
  port: 5044
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
